---
title: 'R Markdown Presentation & Plotly'
author: "M. Klein"
date: "9-1-2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(dplyr)
library(lubridate)
library(xts)
```

```{r loaddata, echo=FALSE, cache=TRUE}
names <-c("Rhenen", "2", "3", "4", "5", "6" ,"Kwintelooijen", "8", "9", "10", "11", "Amerongen", "13","14","15","Hoge Ginkel","17","18","19","20","21","22","Leersum","Zeist","25","26", "27","28","29","Austerlitz")
sectorDaily <- read.csv("sectorAggregate.csv", sep=";")
sectorDaily <- sectorDaily %>% 
    filter(ymd(date) < ymd("2016-11-01"), id %in% c(1,7,12,16,23,24,30)) %>%
    mutate(time=ymd_h(paste(date,hour)),
           date=ymd(date),
           summer_time=ifelse(summer_time=="true",TRUE,FALSE),
           holiday=ifelse(holiday=="true",TRUE,FALSE),
           holidaysNorth=ifelse(holidaysNorth=="true",TRUE,FALSE),
           holidaysMiddle=ifelse(holidaysMiddle=="true",TRUE,FALSE),
           holidaysSouth=ifelse(holidaysSouth=="true",TRUE,FALSE),
           fog=ifelse(fog=="true",TRUE,FALSE),
           rain=ifelse(rain=="true",TRUE,FALSE),
           snow=ifelse(snow=="true",TRUE,FALSE),
           lightning=ifelse(lightning=="true",TRUE,FALSE),
           ice=ifelse(ice=="true",TRUE,FALSE),
           name = names[id])
```

## Summary
This presenation shows the number of rides on the MTB tracks of the Utrechtse Heuvelrug :

- rides per month (january until october)
- rides per day (august until october)
- rides per hour (october)

## Number of Rides per month

```{r}
sectorMonth <- sectorDaily %>% group_by(name, month) %>% summarise(total = sum(count)) 
plot_ly(data=sectorMonth,  x = ~month, y=~total, type="scatter", mode="lines", color=~name)
```

## Number of Rides per day

```{r}
sectorDay <- sectorDaily %>% filter(date >= ymd("2016-08-01")) %>% group_by(name, date) %>% summarise(total = sum(count)) 
plot_ly(data=sectorDay,  x = ~date, y=~total, type="scatter", mode="lines", color=~name)
```

## Number of Rides per hour

```{r}
sectorDaily2 <- sectorDaily %>% arrange(time, id) %>% filter(month==10) 
plot_ly(data=sectorDaily2,  x = ~time, y=~count, type="scatter", mode="lines", color=~name)
```


